image: irgendwr/hugo:latest

stages:
    - test
    - deploy

test:
    stage: test
    script:
        - hugo
    except:
        - master

deploy:
    stage: deploy
    before_script:
        - mkdir -p ~/.ssh
        - echo "$SSH_KEY" > ~/.ssh/key && chmod 600 ~/.ssh/key
        - echo -e "Host *\n\tIdentityFile ~/.ssh/key\n\tStrictHostKeyChecking no\n\tLogLevel error\n" > ~/.ssh/config
    script:
        - hugo --minify
        - rsync -rz --delete public/ $USER@$HOST:$PATH
    only:
        - master
