name: Build Release Image

on:
  workflow_dispatch:
  # Run every day at 5:40.
  schedule:
    - cron:  '40 5 * * *'
jobs:
  buildflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Determine latest un-imaged version
        run: |
          python get_latest_new_release.py
          echo "version=$(cat _version.txt)" >> $GITHUB_ENV
      - name: Quit if no new version
        run: |
          if [ "${{ env.version }}" = "NONE" ]; then
            gh run cancel ${{ github.run_id }}
            gh run watch ${{ github.run_id }}
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update version in code
        run: sed "s/ENV VERSION .*/ENV VERSION ${{ env.version }}/" -i Dockerfile
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image
        run: |
          docker pull node:alpine
          docker build -t nightoo/hugo:${{ env.version }} .
          docker push nightoo/hugo:${{ env.version }}
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.4
        with:
          add: 'Dockerfile'
          message: 'v${{ env.version }}'
          new_branch: 'v${{ env.version }}'
          # Tags are only really used by this script currently
          # remove the "v" to prevent collision with branch name
          tag: '${{ env.version }}'
